# Generated by Django 5.0.6 on 2024-05-24 14:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("root_admin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Actions",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("done_on", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("add_bill", "Added Billed"),
                            ("update_bill", "Updated Billed"),
                            ("add_product", "Added Product"),
                            ("update_product", "Updated Product"),
                            ("add_seller", "Added Seller"),
                            ("update_seller", "Updated seller"),
                            ("add_people", "Added People"),
                            ("update_people", "Updated People"),
                        ],
                        max_length=50,
                    ),
                ),
                ("additional_info", models.TextField()),
                (
                    "admin_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="root_admin.admin",
                    ),
                ),
            ],
        ),
    ]
