# Generated by Django 5.0.6 on 2024-05-24 14:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("root_admin", "0001_initial"),
        ("seller", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("price", models.IntegerField()),
                ("discount", models.IntegerField()),
                ("quantity", models.IntegerField()),
                (
                    "seller_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="seller.seller"
                    ),
                ),
                (
                    "updater_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="root_admin.admin",
                    ),
                ),
            ],
        ),
    ]
